version: "3.8"

services:
  user_service:
    container_name: user_service
    build: ./UserService
    depends_on:
      - "dbpost"
    ports:
      - "8899:8899"

  post_service:
    container_name: post_service
    build: ./PostService
    depends_on:
      - "dbpost"
    ports:
      - "9000:9000"

  api:
    container_name: api_gateway
    build: ./ApiGateway
    depends_on:
      -  "redisdb"
      -  "user_service"
      -  "post_service"
    ports:
      - "8080:8080"



  dbpost:
    container_name: dbpost
    image: postgres:14.1
    environment:
      POSTGRES_DATABASE: postdb
      POSTGRES_USER: kilogram
      POSTGRES_PASSWORD: 112233
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p 5433




    # dbuser:
    #   container_name: dbuser
    #   image: postgres:14.1
    #   environment:
    #     POSTGRES_DATABASE: users
    #     POSTGRES_USER: hatsker
    #     POSTGRES_PASSWORD: 1
    #   ports:
    #     - "5432:5432"
    #   volumes:
    #     - dbdata:/var/lib/postgresql/data
    # volumes:
    #   - ./database/user.sql:docker-entrypoint-initdb.d/user.sql
  redisdb:
    container_name: redisdb
    image:  redis
    ports:
      - "6379:6379"


volumes:
  dbdata: